sudo: required
dist: trusty
language: node_js
node_js:
  - "12"
cache:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm test -- --coverage
after_success:
  - npm install -g codecov
  - codecov < coverage/lcov.info
